config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root "posts#index"
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :pooks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pook.rb
class Pook < ApplicationRecord
  belongs_to :post
end

app/controllers/pooks_controller.rb
class PooksController < ApplicationController
  before_action :set_pook, only: [:show, :edit, :update, :destroy]

  # GET /pooks
  # GET /pooks.json
  def index
    @pooks = Pook.all
  end

  # GET /pooks/1
  # GET /pooks/1.json
  def show
  end

  # GET /pooks/new
  def new
    @pook = Pook.new
  end

  # GET /pooks/1/edit
  def edit
  end

  # POST /pooks
  # POST /pooks.json
  def create
    @pook = Pook.new(pook_params)
    @pook.post_id=params[:post_id]
    @pook.save
  end

  # PATCH/PUT /pooks/1
  # PATCH/PUT /pooks/1.json
  def update
    respond_to do |format|
      if @pook.update(pook_params)
        format.html { redirect_to @pook, notice: 'Pook was successfully updated.' }
        format.json { render :show, status: :ok, location: @pook }
      else
        format.html { render :edit }
        format.json { render json: @pook.errors, status: :unprocessable_entity }
      end
    end

    def update
      @post = Post.find(params[:post_id])
      @pook.pook = params[:pook]
      @pook.save
      
      redirect_to @post
  end
  end

  # DELETE /pooks/1
  # DELETE /pooks/1.json
  def destroy
    @pook.destroy
    respond_to do |format|
      format.html { redirect_to pooks_url, notice: 'Pook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pook
      @pook = @post.pooks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pook_params
      params.require(:pook).permit(:name, :freez, :start, :end, :content, :post_id)
    end
end

app/helpers/pooks_helper.rb
module PooksHelper
end

app/views/pooks/_form.html.erb
<%= form_for(pook) do |f| %>
  <% if pook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pook.errors.count, "error") %> prohibited this pook from being saved:</h2>

      <ul>
      <% pook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :freez %>
    <%= f.check_box :freez %>
  </div>

  <div class="field">
    <%= f.label :start %>
    <%= f.datetime_select :start %>
  </div>

  <div class="field">
    <%= f.label :end %>
    <%= f.datetime_select :end %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.text_field :post_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pooks/_try.html.erb
<%= form_tag("/posts/:post_id/pooks", method: "post") do %>
  <%= label_tag(:name, "이름") %>
  <%= text_field_tag(:name) %>

  <%= label_tag(:start, "시작") %>
  <%= datetime_field_tag(:start) %>

  <%= label_tag(:end, "이름") %>
  <%= datetime_field_tag(:end) %>

  <%= submit_tag("등록") %>
<% end %>

app/views/pooks/edit.html.erb
<h1>Editing Pook</h1>

<%= render 'form', pook: @pook %>

<%= link_to 'Show', @pook %> |
<%= link_to 'Back', pooks_path %>

app/views/pooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pooks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Freez</th>
      <th>Start</th>
      <th>End</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pooks.each do |pook| %>
      <tr>
        <td><%= pook.name %></td>
        <td><%= pook.freez %></td>
        <td><%= pook.start %></td>
        <td><%= pook.end %></td>
        <td><%= pook.content %></td>
        <td><%= link_to 'Show', post_pook_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pook', new_post_pook_path %>

app/views/pooks/new.html.erb
<h1>New Pook</h1>

<%= render 'try', post: @pook %>

<%= link_to 'Back', post_pooks_path %>

app/views/pooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pook.name %>
</p>

<p>
  <strong>Freez:</strong>
  <%= @pook.freez %>
</p>

<p>
  <strong>Start:</strong>
  <%= @pook.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @pook.end %>
</p>

<p>
  <strong>Content:</strong>
  <%= @pook.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @pook.post %>
</p>

<%= link_to 'Edit', edit_post_pook_path(@pook) %> |
<%= link_to 'Back', post_pooks_path %>